services:
    catalogue-db:
        image: weaveworksdemos/catalogue-db:0.3.0
        hostname: catalogue-db
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=fake_password
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=socksdb
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 30s
            timeout: 10s
            retries: 5

    catalogue:
        build:
            context: .
            dockerfile: ./docker/catalogue/Dockerfile
        image: weaveworksdemos/catalogue:latest
        hostname: catalogue
        restart: always
        ports:
            - "80:80"
        cap_drop:
            - all
        cap_add:
            - NET_BIND_SERVICE
        read_only: true
        depends_on:
            catalogue-db:
                condition: service_healthy