name: Test new Implementation
on:
  push:
    branches: [ main ]
#    branches: [ dev ]

jobs:
  build-and-test:
    name: Build and Test Front-End Image
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: fake_password
      MYSQL_DATABASE: socksdb
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    defaults:
      run:
        shell: bash

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Run Docker Compose
        id: docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose-dev.yaml"
        continue-on-error: false

      - name: Check whether the service is alive
        run: docker exec catalogue-catalogue-1 wget -q -s http://localhost:80/health

      - name: Use the service endpoints
        run: docker exec catalogue-catalogue-1 wget -q -s http://localhost:80/catalogue

      - name: Get Logs from Catalogue Container
        run: docker logs catalogue-catalogue-1 > logs.txt || true

      - name: Check for errors in logs
        run: |
          if grep -i "error" logs.txt; then
            echo "Errors found in container logs"
            cat logs.txt
            exit 1
          else
            echo "No errors found in container logs"
          fi
